version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=capes2
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork

  db:
    image: postgres:13
    build: .
    container_name: db
    ports: 
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge
volumes:
  postgres_data:
